/** Optional, component-level locale overrides. Existing label props win. */
export interface ComponentLabels {
    max?: React.ReactNode;
    balance?: React.ReactNode;
    selectAsset?: string;
    copyAddress?: string;
    copiedAddress?: string;
    pasteAddress?: string;
    pending?: React.ReactNode;
    completed?: React.ReactNode;
    failed?: React.ReactNode;
    online?: React.ReactNode;
    degraded?: React.ReactNode;
    offline?: React.ReactNode;
    back?: string;
    copy?: string;
    confirm?: React.ReactNode;
    cancel?: React.ReactNode;
    close?: string;
    today?: React.ReactNode;
    now?: React.ReactNode;
    clearDate?: string;
    clearTime?: string;
    selectDate?: string;
    selectDateRange?: string;
    selectTime?: string;
    previousYear?: string;
    previousMonth?: string;
    nextMonth?: string;
    nextYear?: string;
    hour?: string;
    minute?: string;
    second?: string;
    transactionDetails?: React.ReactNode;
    transactionSummary?: string;
    totalBalance?: React.ReactNode;
    walletBalance?: React.ReactNode;
    balanceHidden?: string;
    viewOnExplorer?: React.ReactNode;
    /** Shared labels for non-wallet primitives. Arrays use Sunday-first / January-first order. */
    carousel?: string;
    previousSlide?: string;
    nextSlide?: string;
    selectSlide?: string;
    goToSlide?: (index: number, count: number) => string;
    pauseAutoplay?: string;
    resumeAutoplay?: string;
    pagination?: string;
    previousPage?: string;
    nextPage?: string;
    pageSizeLabel?: (size: number) => string;
    pageSizeOption?: (size: number) => string;
    pageSizeMenu?: string;
    pageCount?: (total: number) => string;
    jumpToPage?: string;
    jumpToPagePrefix?: string;
    jumpToPageSuffix?: string;
    imageLoadFailed?: string;
    imagePreview?: string;
    closePreview?: string;
    loading?: string;
    footer?: React.ReactNode;
    codeCopy?: string;
    codeCopied?: string;
    codeCopyError?: string;
    codeCopyLabel?: string;
    selectMenu?: string;
    emptyState?: React.ReactNode;
    loadingState?: string;
    notificationClose?: string;
    weekdays?: string[];
    months?: string[];
    dateLabel?: (year: number, month: number, day: number) => string;
    monthLabel?: (month: number) => string;
    yearLabel?: (year: number) => string;
}

export type ComponentLabelOverrides = Partial<ComponentLabels>;
